baseurl: https://giovstechs.it
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: GiansTech.dev

languages:
   en:
    contentDir: content
    languageName: English
    weight: 10
  
   it:
    contentDir: content
    languageName: Italiano
    weight: 20


DefaultContentLanguage: en
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
        - contact 
        - about
        - projects
    featuredImageField: image
    rssFullContent: true
    favicon: 

    footer:
        since: 2022
        customText: Coded with ❤️ by GiovsTech

    dateFormat:
        published:  Jan 25, 2006
        lastUpdated: May 20, 2006 14:18 UTC
    sidebar:
        emoji: 
        subtitle: Young developer of 15 years old. 
        avatar:
            enabled: true
            local: true
            src: img/logo.jpg

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: disqus


    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:

            site: johnds963


            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true

        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true


menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/GiovsTech
          params:
              icon: brand-github

        - identifier: mastodon
          name: Mastodon
          url: https://techhub.social/@giovstechs
          params:
              icon: brand-mastodon

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
